// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqDzklEjvURw8OONtnkfoSY5inxrBuv4',
    appId: '1:239674783869:web:382c5ffd73f45e16e11914',
    messagingSenderId: '239674783869',
    projectId: 'cybereak-d07fa',
    authDomain: 'cybereak-d07fa.firebaseapp.com',
    databaseURL: 'https://cybereak-d07fa.firebaseio.com',
    storageBucket: 'cybereak-d07fa.appspot.com',
    measurementId: 'G-SG6LMK7KG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-KEr2R58r4B7dT1mAMuqY9DzlfVSDfWM',
    appId: '1:239674783869:android:fcdbbafa8ee31645e11914',
    messagingSenderId: '239674783869',
    projectId: 'cybereak-d07fa',
    databaseURL: 'https://cybereak-d07fa.firebaseio.com',
    storageBucket: 'cybereak-d07fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqdGOjDv9UclYjE29yCJR0AaaSi4Xiohk',
    appId: '1:239674783869:ios:403856ea2acc13a8e11914',
    messagingSenderId: '239674783869',
    projectId: 'cybereak-d07fa',
    databaseURL: 'https://cybereak-d07fa.firebaseio.com',
    storageBucket: 'cybereak-d07fa.appspot.com',
    iosClientId: '239674783869-0dr38j9k0d64js4oi3tt16utuc8o1bi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybereak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqdGOjDv9UclYjE29yCJR0AaaSi4Xiohk',
    appId: '1:239674783869:ios:403856ea2acc13a8e11914',
    messagingSenderId: '239674783869',
    projectId: 'cybereak-d07fa',
    databaseURL: 'https://cybereak-d07fa.firebaseio.com',
    storageBucket: 'cybereak-d07fa.appspot.com',
    iosClientId: '239674783869-0dr38j9k0d64js4oi3tt16utuc8o1bi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybereak',
  );
}
